### ISSUE TITLE
Update step in Newton's method

### ISSUE THREAD

**Issue by ovysotska** [niosus/notebooks#4]
Dear @niosus ,

thanks for the informative least-squares notebook.
I have a simple clarification question. 
Should the formula for finding the parameter $h$ be $Hh = -F'(x)$. It occurs right after the formula (8).

Thanks!

**Comment by niosus** [comment]
@ovysotska yep, you're right. :+1: 

There are lots of mistakes in this notebook. See my [thesis](https://www.ipb.uni-bonn.de/pdfs/bogoslavskyi2018phd.pdf) for a correct version.
